# Generated by Django 5.2.14 on 2026-05-25 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_initial'),
        ('resena', '0003_add_clase_to_resena'),
        ('turno', '0004_alter_clase_actividad_alter_clase_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('usuario', 'actividad'), name='unique_usuario_actividad'),
        ),
    ]
