# Generated by Django 5.2.12 on 2026-06-30 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_initial'),
        ('resena', '0004_resena_unique_usuario_actividad'),
        ('turno', '0605_merge_20260629_1635'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resena',
            name='unique_usuario_actividad',
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('usuario', 'clase'), name='unique_usuario_clase'),
        ),
    ]
