# Generated by Django 6.0.5 on 2026-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qr_usado',
            field=models.BooleanField(default=False),
        ),
    ]
