# Generated by Django 6.0.3 on 2026-05-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_initial'),
        ('turno', '0003_add_qr_usado'),
        ('user', '0004_historialusuariobaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='actividad.actividad'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='user.profesor'),
        ),
    ]
