# Generated by Django 5.2.14 on 2026-06-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0004_alter_clase_actividad_alter_clase_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
