# Generated by Django 5.2.14 on 2026-06-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0005_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='turno.salon'),
        ),
    ]
