# Generated by Django 5.2.14 on 2026-06-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0601_abono_turnos_fijos_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='turnos_fijos_ids',
        ),
    ]
