# Generated by Django 5.2.12 on 2026-06-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0007_alter_clase_salon_fk'),
        ('turno', '0602_remove_abono_turnos_fijos_ids'),
    ]

    operations = [
    ]
