# Generated by Django 5.2.12 on 2026-06-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0603_merge_20260624_1153'),
        ('turno', '0603_merge_20260624_1502'),
    ]

    operations = [
    ]
