# Generated by Django 5.2.14 on 2026-06-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0603_merge_20260624_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelacion_tardia',
            field=models.BooleanField(default=False),
        ),
    ]
