# Generated by Django 5.2.12 on 2026-06-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0604_merge_20260628_1448'),
        ('turno', '0604_reserva_cancelacion_tardia'),
    ]

    operations = [
    ]
