# Generated by Django 6.0.5 on 2026-07-03 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_initial'),
        ('turno', '0605_merge_20260629_1635'),
        ('user', '0005_profesor_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo_maximo', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_fijas', to='actividad.actividad')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_fijas', to='user.profesor')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_fijas', to='turno.salon')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='clase_fija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_generadas', to='turno.clasefija'),
        ),
    ]
