# Generated by Django 6.0.5 on 2026-05-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('mercado_pago', 'Mercado Pago'), ('creditos', 'Créditos')], max_length=30),
        ),
    ]
