# Generated by Django 5.2.14 on 2026-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
