# Generated by Django 5.2.12 on 2026-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_pago_payment_id_pago_preference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('mercado_pago', 'Mercado Pago'), ('creditos', 'Créditos'), ('posnet', 'POSNET'), ('transferencia', 'Transferencia')], max_length=30),
        ),
    ]
