# Generated by Django 5.2.14 on 2026-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_historialusuariobaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
